# Generated by Django 5.0.3 on 2024-07-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="api_call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
                ("API Endpoint", models.TextField(blank=True)),
                ("Headers", models.TextField(blank=True, null=True)),
                ("Body", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
