# Generated by Django 5.0.3 on 2024-07-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_api_call_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="api_call",
            name="api_type",
            field=models.TextField(
                choices=[
                    ("get", "GET"),
                    ("post", "POST"),
                    ("patch", "PATCH"),
                    ("put", "PUT"),
                    ("delete", "DELETE"),
                ],
                default="ge",
                max_length=6,
            ),
        ),
    ]
